name: gcloud
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: sudo apt-get update && sudo apt-get install google-cloud-sdk
      - run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 --decode > "$HOME"/gcloud.json
          sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"
      - run: mvn clean package appengine:deploy -Dapp.deploy.projectId=home-12
